### ISSUE TITLE
I am getting the following error after installing and configuring the lib: reply.view is not a function

### ISSUE THREAD

**Issue by pablomarttiins** [fastify/point-of-view#381] opened 2023-08-29 17:39 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.18.0

### Plugin version

8.0.0

### Node.js version

18.16.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04.6 LTS

### Description

After installing the lib and configuring it, I am getting the error: reply.view is not a function

### Steps to Reproduce

Instalei a lib com:

npm i @fastify/view

I performed the configuration in app.ts.

The configuration was done as follows:

app.register(fastifyView, {
    engine: {
        ejs: ejs
    },
    root: path.join(__dirname, 'views'),
    layout: "./templates/template", 
    viewExt: "ejs", 
    propertyName: "render", 
    defaultContext: {
        dev: process.env.NODE_ENV === "dev", 
    },
    options: {},
})

**Comment by gurgunday** [comment] 2023-09-09 17:24
Well, it’s because you set the `propertyName` property to `render`

You should do `reply.render()`, or remove `propertyName` from options

**Comment by gurgunday** [comment] 2023-09-09 17:25
Closing this but feel free to write back if the problem isn’t solved

**Closed by gurgunday** 2023-09-09 17:25 UTC
