### ISSUE TITLE
Usage within async handler function?

### ISSUE THREAD

**Issue by stereosteve** [fastify/point-of-view#82] opened 2018-11-06 20:55 UTC
Calling `reply.view` in an `async` handler function logs an error: 

```
{"level":50,"time":1541536966444,"msg":"Promise may not be fulfilled with 'undefined' when statusCode is not 204","pid":17183,"hostname":"ip-10-10-10-218.ec2.internal","reqId":1,"err":{"type":"Error","message":"Promise may not be fulfilled with 'undefined' when statusCode is not 204","stack":"Error: Promise may not be fulfilled with 'undefined' when statusCode is not 204\n    at /home/steve/ff-pov/node_modules/fastify/lib/wrapThenable.js:18:34"},"v":1}
```

The rendered html will actually arrive at the browser, but the above message will be logged to console.

Here is example server:

```js
const fastify = require("fastify")({
  logger: true
});

fastify.register(require("point-of-view"), {
  engine: {
    nunjucks: require("nunjucks")
  }
});

async function something() {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve(new Date());
    }, 1000);
  });
}

fastify.get("/", async (req, reply) => {
  const t = await something();
  reply.view("/home.html", { text: t });
});

fastify.listen(3000, err => {
  if (err) throw err;
  console.log(`server listening on ${fastify.server.address().port}`);
});
```

Is there a better way to do this?

**Comment by FuyukiWolfer** [comment] 2018-11-26 02:48
I have the same problem :/

**Comment by tojacob** [comment] 2018-12-01 01:08
This also happened to me. Any way to solve it for while?

**Comment by tojacob** [comment] 2018-12-01 02:53
I made this little hack and it worked 😂
I share it in case it serves someone else, while the new API comes out. I do not know how safe this is, I'm only using it while I'm playing with the framework.

```javascript
'use strict';

function message() {
  return new Promise((resolve, reject) => {
    setTimeout(() => resolve('Hey there!'), 1000);
  });
}

function handler(controller) {
  return function(req, reply) {
    controller(req, reply);
  };
}

async function homeController(req, reply) {
  const msg = await message();
  reply.view('home', { msg });
}

async function homeRoute(fastify, options) {
  fastify.get('/', handler(homeController));
}

module.exports = homeRoute;
```

**Comment by FuyukiWolfer** [comment] 2018-12-02 03:46
Apparently if you use Marko.js this error does not happen too.

**Comment by charlesread** [comment] 2019-02-15 13:36
I attempted to skirt this by rendering the HTML into a variable with the documented `awync fastify.view()` and then just return that, but it never resolves.

**Comment by thearegee** [comment] 2019-03-01 22:45
I'm having a similar issue, using `ejs` inside my `notFound` decorator where I want to be able to render an error page from a template. I've tried all the options in docs and creating another decorator like above and although it renders HTML it always throws this error in my logs:

`"FST_ERR_PROMISE_NOT_FULLFILLED: Promise may not be fulfilled with 'undefined' when statusCode is not 204"`

**Comment by huaentandd01** [comment] 2019-04-24 10:26
mark

**Comment by qxw180** [comment] 2019-10-30 13:13
mark

**Comment by dmytro-balytskyi** [comment] 2019-10-31 11:52
Hi
I tested various options to solve a similar problem.

After that, I decided to generate the HTML document directly through the **reply.send** method and found that the problem was in this block of code.

The Send Method has API 
`.then (fullfilled, rejected)`

I found that **fullfilled** returns an undefined value, document generation breaks off and browser closes the window.

The error occurs when I try to generate a block with a built-in script, an example script below.

```
<script type="text/javascript">
let accessToken = document.getElementById('access')
let refreshToken = document.getElementById('refresh')

accessToken = accessToken.innerHTML
refreshToken = refreshToken.innerHTML
                                    
console.log('AC token ', accessToken)
console.log('RF token ', refreshToken)

if (accessToken && refreshToken) {
    let app = null;

    if (window.opener) {
           app = window.opener
     } else if (crossDomainWindow.opener) {
           app = window.crossDomainWindow.opener
     }

     app.postMessage({ access: accessToken, refresh: refreshToken, status: true }, 'http://localhost:3000')
 }
</script>
```

I’ll try to explore the code of the fastify reply.send method, maybe my message will help someone, if I find a solution, I’ll write.

**Comment by mcollina** [comment] 2019-10-31 13:31
You can just return the reply object in the async handler. It should work.

**Comment by dmytro-balytskyi** [comment] 2019-11-01 12:47
> You can just return the reply object in the async handler. It should work.

Thank you very much. I already found your previous answers on this topic. Everything works fine.

**Comment by red1** [comment] 2019-12-03 13:51
> You can just return the reply object in the async handler. It should work.

@mcollina Can you provide an example ? I tried to return reply and I have a 500 error

**Comment by red1** [comment] 2019-12-06 09:47
Thanks @mcollina for the example 
I had similar code : 
```
var oRes = await Page.paginate({ key: some_key});
reply.type('text/javascript').view((oRes.docs.length== 0) ? 'noresults.ejs' :'mytemplate.ejs', oRes);
return reply;
```
I got a 500 when i return reply :

```
res: {
      "statusCode": 500
    }
    err: {
      "type": "FastifyError",
      "message": "FST_ERR_REP_INVALID_PAYLOAD_TYPE: Attempted to send payload of invalid type 'object'. Expected a string or Buffer.",
      "stack":
          FastifyError [FST_ERR_REP_INVALID_PAYLOAD_TYPE]: FST_ERR_REP_INVALID_PAYLOAD_TYPE: Attempted to send payload of invalid type 'object'. Expected a string or Buffer.
              at onSendEnd (/home/projects/sample-api/node_modules/fastify/lib/reply.js:320:11)
              at onSendHook (/home/projects/sample-api/node_modules/fastify/lib/reply.js:282:5)
              at _Reply.Reply.send (/home/projects/sample-api/node_modules/fastify/lib/reply.js:139:3)
              at /home/projects/clever-api/node_modules/fastify/lib/wrapThenable.js:27:15
              at process._tickCallback (internal/process/next_tick.js:68:7)
      "name": "FastifyError [FST_ERR_REP_INVALID_PAYLOAD_TYPE]",
      "code": "FST_ERR_REP_INVALID_PAYLOAD_TYPE",
      "statusCode": 500
    }
```
And same error than the first post when I don't

Note that I use fastify-swagger, and the promise paginate is from Mongoose mongoose-paginate-v2

**Comment by mcollina** [comment] 2019-12-06 09:53
Which version of Fastify are you using? You should be on the latest one of the v2 series, as the fix for this is somewhat a recent development.

**Comment by red1** [comment] 2019-12-06 11:15
oh okay Iwas using 2.6.0, 
I updated fastify and it works now ! Thanks

**Closed** 2019-12-11 12:57 UTC
Labels: good first issue

**Comment by khushal123** [comment] 2021-11-20 14:42
reply.view itself is not available for me with typescript fastify-cli

**Comment by climba03003** [comment] 2021-11-20 14:44
> reply.view itself is not available for me with typescript fastify-cli

Please open a new issue for your problem. Remember to attach the reproducible code snippets for debugging.
